spring.application.name=no-dues-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/nodues_sboot
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=R0h!t@2026JwtSecretKey#SpringBoot$NoDuesApplication
jwt.expiration=86400000
